name: TestingUbuntu

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    test-ubuntu:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.13"]

        env:
            USE_MKDOCS: ${{ secrets.USE_MKDOCS }}

        steps:
            - uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v3
              with:
                  version: "0.4.16"
                  enable-cache: true

            - name: Set up Python ${{ matrix.python-version }}
              run: uv python install ${{ matrix.python-version }}

            - name: Install dependencies
              run: uv sync --python ${{ matrix.python-version }}

            - name: Test import
              run: |
                  uv run python -c "import geemap; print('geemap import successful')"

            - name: Running tests
              run: |
                  uv run python -m unittest discover tests/
