on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

name: Test Python 3.11
jobs:
    test-ubuntu:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.11-dev"]
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install GDAL
              run: |
                  python -m pip install --upgrade pip
                  pip install --no-cache-dir Cython
                  pip install --find-links=https://girder.github.io/large_image_wheels --no-cache GDAL
            - name: Test GDAL installation
              run: |
                  python -c "from osgeo import gdal"
                  gdalinfo --version
            - name: Install dependencies
              run: |
                  pip install -r requirements.txt
                  pip install codespell
                  pip install .
            - name: Discover typos with codespell
              run: codespell --skip="*.csv,*.geojson,*.json,*.yml*.js,*.html,*cff,*.pdf" --ignore-words-list="aci,acount,acounts,fallow,ges,hart,hist,nd,ned,ois,wqs,watermask"
            - name: PKG-TEST
              run: |
                  python -m unittest discover tests/
              env:
                  HEREMAPS_API_KEY: ${{ secrets.HEREMAPS_API_KEY }}
                  PLANET_API_KEY: ${{ secrets.PLANET_API_KEY }}
                  EARTHENGINE_TOKEN: ${{ secrets.EARTHENGINE_TOKEN }}
